#include "draw.h"
#include "gba.h"
#include "myLib.h"
#include <stdio.h>
#include "images/TetrisTitleScreen.h"
#include "images/GameOver.h"
#include "images/background.h"
#include "images/cooldog.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

static void drawCurrBlock(Block curr, u16 color, u16 outline) {
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            if (curr.grid[i][j]) {
                drawRectDMA(INIT_ROW + ((i + curr.r) * PIX),
                            INIT_COL + ((j + curr.c) * PIX),
                            PIX, PIX, outline);
                drawRectDMA(INIT_ROW + ((i + curr.r) * PIX) + 1,
                            INIT_COL + ((j + curr.c) * PIX) + 1,
                            PIX - 1, PIX - 1, color);
            }
        }
    }
}

static void drawBoard(u16 board[20][10], u16 outline) {
    for (int i = 0; i < 20; i++) {
        for (int j = 0; j < 10; j++) {
            if (board[i][j] != 0 ) {
                drawRectDMA(INIT_ROW + (i * PIX), INIT_COL + (j * PIX), PIX, PIX, outline);
                drawRectDMA(INIT_ROW + (i * PIX) + 1, INIT_COL + (j * PIX) + 1, PIX - 1, PIX - 1, board[i][j]);
            } else {
                drawRectDMA(INIT_ROW + (i * PIX), INIT_COL + (j * PIX), PIX, PIX, BLACK);
            }
        }
    }
}

static void drawScoreLevel(AppState *state, u16 color) {
    char strPoint[50];
    char strLevel[50];
    sprintf(strPoint, "%d", state->points);
    sprintf(strLevel, "%d", state->level);
    drawString(INIT_COL + 120, INIT_ROW, strPoint, color);
    drawString(INIT_COL + 120, INIT_ROW + 10, strLevel, color);
}

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    drawFullScreenImageDMA(background);
    drawRectDMA(INIT_ROW - 4, INIT_COL - 4, PIX * BOARD_WIDTH + 8, PIX * BOARD_HEIGHT + 8, BLACK);
    drawRectDMA(INIT_ROW - 2, INIT_COL - 2, PIX * BOARD_WIDTH + 4, PIX * BOARD_HEIGHT + 4, WHITE);
    drawRectDMA(INIT_ROW, INIT_COL, PIX * BOARD_WIDTH, PIX * BOARD_HEIGHT, BLACK);
    drawString(INIT_COL + 80, INIT_ROW, "Score: ", BLACK);
    drawString(INIT_COL + 80, INIT_ROW + 10, "Level: ", BLACK);
    drawScoreLevel(state, BLACK);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    drawCurrBlock(state->currBlock, BLACK, BLACK);
    drawScoreLevel(state, WHITE);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.

    if (state->placed == 1) {
        drawBoard(state->BOARD, ALMOSTWHITE);
        if (state->tetris == 1) {
            drawImageDMA(INIT_ROW - 10, INIT_COL + 130, 39, 40, cooldog);
        } else {
            drawRectDMA(INIT_ROW - 10, INIT_COL + 130, 39, 40, WHITE);
        }
        state->placed = 0;
    }
    drawCurrBlock(state->currBlock, state->currBlock.color, ALMOSTWHITE);
    drawScoreLevel(state, BLACK);
}
